// Generated by scripts/paper-buddy-unfold/build.mjs. Edit component.mjs.
import './PaperBuddyUnfold.css'

export interface PaperBuddyUnfoldProps {
  loop?: boolean
  paused?: boolean
  open?: boolean
  purpose?: 'loading' | 'welcome'
  replayKey?: string | number
  className?: string
}

const [blueSrc, backSrc, shadeSrc] = ["/ip/paper-buddy-unfold/blue-buddy.png","/ip/paper-buddy-unfold/blue-buddy-back.png","/ip/paper-buddy-unfold/blue-buddy-shade.png"]

/** A single blue paper mascot. Static PNG textures; CSS owns folding and playback. */
export function PaperBuddyUnfold({ loop = true, paused = false, open = false, purpose = 'loading', replayKey = 0, className = '' }: PaperBuddyUnfoldProps) {
  const classes = ['buddy-unfold', loop ? 'buddy-unfold-loop' : 'buddy-unfold-once', 'buddy-unfold-' + purpose, paused ? 'is-paused' : '', open ? 'is-open' : '', className].filter(Boolean).join(' ')
  return <div key={replayKey} className={classes} aria-hidden="true">
    <div className="buddy-unfold-stage">
      <div className="buddy-unfold-character buddy-unfold-blue">
        <div className="buddy-fold-sheet">
          <div className="buddy-fold-center"><img className="buddy-fold-image" src={blueSrc} alt="" draggable={false} /><img className="buddy-fold-image buddy-fold-shade" src={shadeSrc} alt="" draggable={false} /></div>
          <div className="buddy-fold-wing buddy-fold-left">
          <div className="buddy-fold-face buddy-fold-front"><div className="buddy-fold-clip"><img className="buddy-fold-image" src={blueSrc} alt="" draggable={false} /><img className="buddy-fold-image buddy-fold-shade" src={shadeSrc} alt="" draggable={false} /></div></div>
          <div className="buddy-fold-face buddy-fold-back"><div className="buddy-fold-clip"><img className="buddy-fold-image" src={backSrc} alt="" draggable={false} /></div></div>
        </div>
          <div className="buddy-fold-wing buddy-fold-right">
          <div className="buddy-fold-face buddy-fold-front"><div className="buddy-fold-clip"><img className="buddy-fold-image" src={blueSrc} alt="" draggable={false} /><img className="buddy-fold-image buddy-fold-shade" src={shadeSrc} alt="" draggable={false} /></div></div>
          <div className="buddy-fold-face buddy-fold-back"><div className="buddy-fold-clip"><img className="buddy-fold-image" src={backSrc} alt="" draggable={false} /></div></div>
        </div>
          <img className="buddy-fold-whole" src={blueSrc} alt="" draggable={false} />
        </div>
      </div>
    </div>
  </div>
}
