import { View } from '@tarojs/components'
import type { CSSProperties } from 'react'
import icons from './icons-data.json'

export interface IconProps { size?: number | string; strokeWidth?: number | string; className?: string; color?: string; fill?: string; style?: CSSProperties; 'aria-hidden'?: boolean | 'true' | 'false' }
function makeIcon(name: keyof typeof icons) {
  return function Icon({ size = 24, strokeWidth = 2, className = '', color, fill = 'none', style }: IconProps) {
    const svg = icons[name].replace(/stroke-width="[^"]*"/, `stroke-width="${strokeWidth}"`).replace(/fill="none"/, `fill="${fill === 'none' ? 'none' : '#000'}"`)
    const mask = `url("data:image/svg+xml,${encodeURIComponent(svg)}")`
    return <View className={`h5-svg tietie-icon ${className}`} style={{ width: typeof size === 'number' ? `${size}px` : size, height: typeof size === 'number' ? `${size}px` : size, color, backgroundColor: 'currentColor', maskImage: mask, WebkitMaskImage: mask, maskSize: '100% 100%', WebkitMaskSize: '100% 100%', maskRepeat: 'no-repeat', WebkitMaskRepeat: 'no-repeat', ...style }} />
  }
}
export const ArrowLeft = makeIcon('ArrowLeft')
export const ArrowRight = makeIcon('ArrowRight')
export const ArrowUp = makeIcon('ArrowUp')
export const ArrowUpRight = makeIcon('ArrowUpRight')
export const AtSign = makeIcon('AtSign')
export const Bell = makeIcon('Bell')
export const CircleHelp = makeIcon('CircleHelp')
export const BriefcaseBusiness = makeIcon('BriefcaseBusiness')
export const Cake = makeIcon('Cake')
export const CakeSlice = makeIcon('CakeSlice')
export const CalendarDays = makeIcon('CalendarDays')
export const Check = makeIcon('Check')
export const ChevronDown = makeIcon('ChevronDown')
export const ChevronLeft = makeIcon('ChevronLeft')
export const ChevronRight = makeIcon('ChevronRight')
export const CircleUserRound = makeIcon('CircleUserRound')
export const Clock3 = makeIcon('Clock3')
export const Cloud = makeIcon('Cloud')
export const CloudFog = makeIcon('CloudFog')
export const CloudLightning = makeIcon('CloudLightning')
export const CloudMoon = makeIcon('CloudMoon')
export const CloudRain = makeIcon('CloudRain')
export const CloudSnow = makeIcon('CloudSnow')
export const CloudSun = makeIcon('CloudSun')
export const Compass = makeIcon('Compass')
export const Copy = makeIcon('Copy')
export const Ellipsis = makeIcon('Ellipsis')
export const ExternalLink = makeIcon('ExternalLink')
export const EyeOff = makeIcon('EyeOff')
export const FileSpreadsheet = makeIcon('FileSpreadsheet')
export const FileText = makeIcon('FileText')
export const Flag = makeIcon('Flag')
export const Flower2 = makeIcon('Flower2')
export const Gem = makeIcon('Gem')
export const Gift = makeIcon('Gift')
export const GraduationCap = makeIcon('GraduationCap')
export const Hand = makeIcon('Hand')
export const Hourglass = makeIcon('Hourglass')
export const House = makeIcon('House')
export const Image = makeIcon('Image')
export const Leaf = makeIcon('Leaf')
export const Link = makeIcon('Link')
export const Link2 = makeIcon('Link2')
export const LockKeyhole = makeIcon('LockKeyhole')
export const LogIn = makeIcon('LogIn')
export const LogOut = makeIcon('LogOut')
export const MapPin = makeIcon('MapPin')
export const MessageCircle = makeIcon('MessageCircle')
export const Mic = makeIcon('Mic')
export const Moon = makeIcon('Moon')
export const Mountain = makeIcon('Mountain')
export const Music = makeIcon('Music')
export const Orbit = makeIcon('Orbit')
export const Paperclip = makeIcon('Paperclip')
export const PartyPopper = makeIcon('PartyPopper')
export const PawPrint = makeIcon('PawPrint')
export const Pencil = makeIcon('Pencil')
export const Pin = makeIcon('Pin')
export const Plus = makeIcon('Plus')
export const RefreshCw = makeIcon('RefreshCw')
export const Repeat2 = makeIcon('Repeat2')
export const Shirt = makeIcon('Shirt')
export const Sparkle = makeIcon('Sparkle')
export const Sparkles = makeIcon('Sparkles')
export const Square = makeIcon('Square')
export const Star = makeIcon('Star')
export const Sun = makeIcon('Sun')
export const Trophy = makeIcon('Trophy')
export const Umbrella = makeIcon('Umbrella')
export const Unlink = makeIcon('Unlink')
export const UserPlus = makeIcon('UserPlus')
export const UserRound = makeIcon('UserRound')
export const UsersRound = makeIcon('UsersRound')
export const Wind = makeIcon('Wind')
export const X = makeIcon('X')
