// Generated by scripts/paper-buddy-unfold/build.mjs. Edit component.mjs.
import { Image, View } from '@tarojs/components'
import './PaperBuddyUnfold.css'

export interface PaperBuddyUnfoldProps {
  loop?: boolean
  paused?: boolean
  open?: boolean
  purpose?: 'loading' | 'welcome'
  replayKey?: string | number
  className?: string
}

const [blueSrc, backSrc, shadeSrc] = ["/assets/ip/paper-buddy-unfold/blue-buddy.png","/assets/ip/paper-buddy-unfold/blue-buddy-back.png","/assets/ip/paper-buddy-unfold/blue-buddy-shade.png"]

/** A single blue paper mascot. Static PNG textures; CSS owns folding and playback. */
export function PaperBuddyUnfold({ loop = true, paused = false, open = false, purpose = 'loading', replayKey = 0, className = '' }: PaperBuddyUnfoldProps) {
  const classes = ['buddy-unfold', loop ? 'buddy-unfold-loop' : 'buddy-unfold-once', 'buddy-unfold-' + purpose, paused ? 'is-paused' : '', open ? 'is-open' : '', className].filter(Boolean).join(' ')
  return <View key={replayKey} className={classes} aria-hidden>
    <View className="buddy-unfold-stage">
      <View className="buddy-unfold-character buddy-unfold-blue">
        <View className="buddy-fold-sheet">
          <View className="buddy-fold-center"><Image className="buddy-fold-image" src={blueSrc} mode="aspectFit" /><Image className="buddy-fold-image buddy-fold-shade" src={shadeSrc} mode="aspectFit" /></View>
          <View className="buddy-fold-wing buddy-fold-left">
          <View className="buddy-fold-face buddy-fold-front"><View className="buddy-fold-clip"><Image className="buddy-fold-image" src={blueSrc} mode="aspectFit" /><Image className="buddy-fold-image buddy-fold-shade" src={shadeSrc} mode="aspectFit" /></View></View>
          <View className="buddy-fold-face buddy-fold-back"><View className="buddy-fold-clip"><Image className="buddy-fold-image" src={backSrc} mode="aspectFit" /></View></View>
        </View>
          <View className="buddy-fold-wing buddy-fold-right">
          <View className="buddy-fold-face buddy-fold-front"><View className="buddy-fold-clip"><Image className="buddy-fold-image" src={blueSrc} mode="aspectFit" /><Image className="buddy-fold-image buddy-fold-shade" src={shadeSrc} mode="aspectFit" /></View></View>
          <View className="buddy-fold-face buddy-fold-back"><View className="buddy-fold-clip"><Image className="buddy-fold-image" src={backSrc} mode="aspectFit" /></View></View>
        </View>
          <Image className="buddy-fold-whole" src={blueSrc} mode="aspectFit" />
        </View>
      </View>
    </View>
  </View>
}
